[build]
	command = "yarn build"
	publish = "build"

[images]
  remote_images = ["https://static.btcmap.org/images/.*", "https://www.openstreetmap.org/.*", "https://avatars.githubusercontent.com/.*" ]

[functions]
  included_files = ["./static/fonts/*.ttf"]
