name: ESLint, Prettier, build CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: install modules
        run: yarn

      - name: run prettier
        run: yarn run format

      - name: run eslint
        run: yarn run lint

      - name: run check
        run: yarn run check

      - name: run typecheck
        run: yarn run typecheck
        continue-on-error: true

      - name: create .env
        run: cp .env.example .env

      - name: build app
        run: yarn run build
