name: ESLint, Prettier, build CI

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: install modules
        run: yarn

      - name: run eslint
        run: yarn eslint

      - name: run prettier
        run: yarn lint

      - name: create .env
        run: cp .env.example .env

      - name: build app
        run: yarn build
